language: node_js
node_js:
  - '0.8'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'gem install sass'
  - 'gem install compass'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"  
